### PR TITLE
Feature: plugin system

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR adds support for plugins.

Plugins have to export two fields. `pluginName` and `pluginCode` and have access to the `migrateMongo` object with all needed methods.

The following is an example plugin which connects to the database and only outputs `ok`.

Loading a plugin is possible through `--plugin path-to-file`, multiple plugins can be loaded using `--plugin path-to-file --plugin another-path-to-file`.

I will also update the README then and I think we can use the example for the tests.
What do you think?

```javascript
const program = require("commander");

module.exports = (migrateMongo) => {
    function testit(migrateMongo){
        migrateMongo.database
            .connect()
            .then(db => migrateMongo.status(db))
            .then(statusItems => {
                console.log('ok')
                process.exit(0);
            })
            .catch(err => {
                console.error(err);
            });
    }
    
    program
      .command("test")
      .description("test print the changelog of the database")
      .option("-f --file <file>", "use a custom config file")
      .action(options => {
          testit(migrateMongo)
      });

      return {
          pluginName: "test",
          pluginCode: testit
      };
};
```

##### Checklist

- [ ] `npm test` passes and has 100% coverage
- [ ] README.md is updated

### CODE REVIEW

**Comment by DanielRuf** [comment]
Bukp.

**Comment by DanielRuf** [comment]
Bump.

**Comment by seppevs** [comment]
Thank you for your contribution, and sorry for the late reply.
What is the added value of this? I also don't like that you added commander stuff into `lib/migrate-mongo.js`. Commander stuff belongs in `bin/migrate-mongo.js`.

**Comment by DanielRuf** [comment]
This is meant to implement a plugin system which can add more commands to the migrate-mongo CLI and add new features through that.

We can also move the part about commander or use the readline module or another approach. This is not the final version of this feature proposal.

**Comment by seppevs** [comment]
Sorry, but I don't see the added value of this. I'm closing this PR.

**Comment by DanielRuf** [comment]
Ok, thanks for the feedback. Then it's probably best we create a fork with this feature.

**Pull request closed without merging**
