### PR TITLE
Upgrade mongodb to version 6

### PR DESCRIPTION
**Pull request by klassm**
##### Checklist

- [x] `npm test` passes and has 100% coverage
- [x] README.md is updated

### CODE REVIEW

**Comment by klassm** [comment]
Afterwards we also need to adapt the types, analogous to this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65307/commits/82ca22fe49a2a85e6572703dd0147330134eb491).

**Comment by dgg** [comment]
My team is also blocked by this issue, could this PR be prioritized somehow?
We are not blocked by the types though, as we using JS to run the migrations

**Comment by klassm** [comment]
@seppevs is there a chance to get this merged?

**Comment by seppevs** [comment]
Merged and landed in v11.0.0. Sorry for the delay.

**Comment by suneab** [comment]
Thank you @seppevs and @klassm !

**Comment by klassm** [comment]
Typings PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66827

**Pull request merged**
