### PR TITLE
feat: allow config to be passed via api

### PR DESCRIPTION
**Pull request by powderham**
Guys,

This is my proposal for creating an instance of `migrateMongo` from a constructor, passing config via api. It introduces no regressions (Although it does introduce some code duplication)

It's not ready for merging because it has no tests or an updated readme.

Is this a direction we would like to go in, if so I'd appreciate some help getting it ready for a PR.

### CODE REVIEW

**Comment by seppevs** [comment]
Thank you for your contribution. I will look into it when I find the time.
However, do you mind to leave out the babel? Node 7.x or higher offers us enough ES6 goodness imho.

**Comment by powderham** [comment]
Yes, i'm happy to leave it out if we decide we want to go that way.

I started using es6 without linting errors then when I tried to import it, thought the quicker (future proof) solution was to add babel rather than go back. If we want to merge my changes in, then we can look at making the code DRY-er and revert back.

**Comment by joelmukuthu** [comment]
Hi,

I'd also recommend leaving babel out, at least out of this PR. It's easier to review your actual changes and you'll get a faster turn-around time. On a related note, generated files (by babel, minifiers etc) shouldn't be checked into git, especially for a module that's only used in node and not on the browser.

Best,
Joel

**Comment by salesh** [comment]
Guys can we get this up?

**Comment by salesh** [comment]
Bump again!

Is it rly possible that there is no 1h to just check this great contribution of @powderham  ?

**Comment by seppevs** [comment]
Sorry, I'm very busy at the moment.
The problem is that the PR of @powderham added Babel which I do not want. I will try to implement the fix myself (but I have not much time), otherwise .. feel free to submit a PR (without adding Babel stuff).

**Comment by powderham** [comment]
Ok guys I'm looking in to this now

**Comment by powderham** [comment]
ping @seppevs @ahvetskovich @joelmukuthu @salesh anyone got time to check this?

**Comment by Phoscur** [comment]
What's the status on this?
Considering this package better than umzug because of the appliedAt tracking!
Would be great to wrap it to a project specific api.

**Comment by seppevs** [comment]
I finally found some time and implemented this feature. It's in migrate-mongo v8.1.1 or later.
See [this section in the README](https://github.com/seppevs/migrate-mongo#configsetyourconfigobject) for more details.

I'm closing this PR.

**Pull request closed without merging**
